##################
# Circinus
# Servicios de Postgres y Shiny en conjunto para laboratorio de datos
##################

version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./backup:/backup
      - ./backup/init.sh:/docker-entrypoint-initdb.d/init.sh
  shiny:
    image: nytio/circinus:v2023
    restart: "no"
#    environment:
#      - LANG=es_MX.UTF-8  
#      - LANGUAGE=es_MX:es
#      - LC_ALL=es_MX.UTF-8
#      - TZ=America/Mexico_City
    ports:
      - '80:3838'
    volumes:
      - ./app/shiny:/srv/shiny-server/
      - ./log:/var/log/shiny-server/
      - ./backup/odbc.ini:/etc/odbc.ini
      - ./app/shiny-server.conf:/etc/shiny-server/shiny-server.conf
#      - ./app/.Rprofile:/home/shiny/.Rprofile
    depends_on:
      - db
volumes:
  db:
    driver: local
networks:
  red_local:
    external: true
