name: publish
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CIRCINUS }}
      - name: Build
        run: docker build --no-cache -t ghcr.io/docker/circinus:v2023 -f docker/v2023/Dockerfile .
      - name: Push
        run: docker push ghcr.io/docker/circinus:v2023
