name: publish
on:
  push:
    branches: ["main"]
    paths:
      - 'docker/v2024/Dockerfile'
jobs:
  create-docker-image-v2024:
    if: contains(github.event.push.commits[*].added, 'docker/v2024/Dockerfile') || contains(github.event.push.commits[*].modified, 'docker/v2024/Dockerfile')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CIRCINUS }}
      - name: Build ghcr.io/nytio/docker:v2024
        run: docker build --no-cache -t ghcr.io/nytio/docker:v2024 -f docker/v2024/Dockerfile .
      - name: Push ghcr.io/nytio/docker:v2024
        run: docker push ghcr.io/nytio/docker:v2024
